### ISSUE TITLE
Region is missing error

### ISSUE THREAD

**Issue by SafakB** [nhathvv/rest-api-twitter#1]
Error : `throw new Error("Region is missing");`

Full Error :
```sh
D:\node\backend-nodejs-api-twitter\node_modules\@smithy\config-resolver\dist-cjs\index.js:134
    throw new Error("Region is missing");
          ^
Error: Region is missing
    at resolveRegionConfig (D:\node\backend-nodejs-api-twitter\node_modules\@smithy\config-resolver\dist-cjs\index.js:134:11)
    at new SESClient (D:\node\backend-nodejs-api-twitter\node_modules\@aws-sdk\client-ses\dist-cjs\index.js:256:70)
    at Object.<anonymous> (D:\node\backend-nodejs-api-twitter\src\utils\email.ts:7:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (D:\node\backend-nodejs-api-twitter\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (D:\node\backend-nodejs-api-twitter\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
```

How to bypass email sending ? Is possible ?

**Comment by nhathvv** [comment]
You can comment the line `await sendVerifyRegisterEmail(payload.email, email_verify_token)`, if you want to get the token to verify the email, you can use the value printed out in `console.log('email_verify_token', email_verify_token)`
```ts
   async register(payload: RegisterReqBody) {
    const user_id = new ObjectId()
    const email_verify_token = (await this.signEmailVerifyToken({
      user_id: user_id.toString(),
      verify: UserVerifyStatus.Unverified
    })) as string
    console.log('email_verify_token', email_verify_token)
    console.log(payload.email)
    const user = new User({
      ...payload,
      _id: user_id,
      username: `user${user_id.toString()}`,
      email_verify_token,
      date_of_birth: new Date(payload.date_of_birth),
      password: hashPassword(payload.password)
    })
    await databaseService.users.insertOne(user)
    const [access_token, refresh_token] = await this.signAccessTokenAndRefreshToken({
      user_id: user_id.toString(),
      verify: UserVerifyStatus.Unverified
    })
    const { iat, exp } = await this.decodeRefreshToken(refresh_token)
    await databaseService.refreshTokens.insertOne(
      new RefreshTokens({
        user_id: new ObjectId(user_id),
        token: refresh_token,
        iat,
        exp
      })
    )
    // await sendVerifyRegisterEmail(payload.email, email_verify_token)
    return {
      access_token,
      refresh_token
    }
  }
```
